version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    allow:
      - dependency-name: "*"
      - dependency-type: "all"
